---
:tag:          'ruby-test'
:verbose:      true
:pidfile:      ./tmp/pids/sidekiq.pid
:logfile:      ./log/sidekiq_ruby-test.log
development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - mailers
  - cron
